### ISSUE TITLE
JDBC Source with SQL server

### ISSUE THREAD

**Issue by thesynapses** [spring-projects/spring-xd#1521]
There seems to be an issue with connecting SpringXD to SQL server.
I downloaded and inserted a sqljdbc4.jar and sqljdbc.jar in /opt/pivotal/spring-xd/xd/lib directory.
Once I deploy a stream I get a strange error on 1433/DB-NAME not being the correct port.

I have tried changing ports, giving Database string as typical "database=DB-NAME" value but nothing seems to work.

Please advice.

**Comment by trisberg** [comment]
can you share the JDBC URL you are using and the exception/stack trace

**Comment by artembilan** [comment]
@thesynapses, isn't this your question: http://stackoverflow.com/questions/29261676/springxd-1-1-0-jdbc-source-connection-issues-with-sql-server ?

@trisberg , can we somehow overcome that `;` issue in the stream definition?

The correct SQL Server URL is: https://msdn.microsoft.com/en-us/library/ms378428%28v=sql.110%29.aspx

**Comment by thesynapses** [comment]
Yes our question is in stack as well.
No ; doesn't do the trick. It is called out as an exception.

String that we are using is similar to any database string except that the driver is Microsoft here.

(We used a similar string  for Greenplum and HAWQ and yhat worked. It did however gave some connection pool error after 60sec of running. That is for another thread)


stream create connectiontest --definition "jdbc --url=jdbc:sqlserver://databaseIP:1433/Databasename
                                            --driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver --username=sample
                                            --password=***** --query= 'SELECT * FROM schema.tablename' |log" --deploy

We get-

port 1433/databasename is not valid


Regards,
Sureel

On Mar 25, 2015, at 2:58 PM, Artem Bilan <notifications@github.com<mailto:notifications@github.com>> wrote:


@thesynapses<https://github.com/thesynapses>, isn't this your question: http://stackoverflow.com/questions/29261676/springxd-1-1-0-jdbc-source-connection-issues-with-sql-server ?

@trisberg<https://github.com/trisberg> , can we somehow overcome that ; issue in the stream definition?

The correct SQL Server URL is: https://msdn.microsoft.com/en-us/library/ms378428%28v=sql.110%29.aspx

**Comment by trisberg** [comment]
if you need to put URL properties in the URL just single-quote the URL expression like this:

```
 --url='jdbc:sqlserver://databaseIP:1433;database=Database_name'
```

**Comment by thesynapses** [comment]
It doesn't not work. Gives exception on ";"


Regards,
Sureel

On Mar 25, 2015, at 3:28 PM, Thomas Risberg <notifications@github.com<mailto:notifications@github.com>> wrote:


if you need to put URL properties in the URL just single-quote the URL expression like this:

 --url='jdbc:sqlserver://databaseIP:1433;database=Database_name'

**Comment by trisberg** [comment]
Not sure I understand what 'Gives exception on ";"' mean? can you post your complete stream command and the full error text?

**Comment by thesynapses** [comment]
I ran:
stream create gpt --definition "jdbc --url='jdbc:sqlserver://IP:1433;database=DBNAME' --driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver --username=USERNAME --password=PASSWORD --query= 'SELECT * FROM TABLE' |log" –deploy

Output waited for sometime and timed out

2015-03-25 21:31:57,825 1.1.0.RELEASE ERROR CuratorFramework-0 imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:695)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:813)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:779)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$400(CuratorFrameworkImpl.java:58)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:265)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)


Regards,

Sureel Bhurat
(312)380-1857

**Comment by thesynapses** [comment]
Additonally - it freezes the system because it runs out of memory before garbage collection kicks in. I had to reboot the system. Not a big deal but still something to look at later.

**Comment by trisberg** [comment]
How big is your table? If you try to read a very large table in one go then you will likely have memory problems

**Comment by thesynapses** [comment]
Okay perfect. I did a select count(*) and it worked. It does spit out a connection error after sometime and resumes. Basically the string works (YAY!!) but I see intermittent connection issues. 

5-03-25 21:45:44,494 1.1.0.RELEASE  INFO task-scheduler-2 sink.gpt - {=697330}
2015-03-25 21:45:49,542 1.1.0.RELEASE  INFO task-scheduler-1 sink.gpt - {=697330}
2015-03-25 21:45:54,585 1.1.0.RELEASE  INFO task-scheduler-3 sink.gpt - {=697330}
2015-03-25 21:45:59,658 1.1.0.RELEASE  INFO task-scheduler-2 sink.gpt - {=697330}
2015-03-25 21:46:04,678 1.1.0.RELEASE ERROR task-scheduler-4 handler.LoggingHandler - org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException: Failed to validate a newly established connection.
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:245)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:457)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy127.call(Unknown Source)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller$1.run(AbstractPollingEndpoint.java:298)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor$1.run(ErrorHandlingTaskExecutor.java:52)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:49)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.run(AbstractPollingEndpoint.java:292)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.SQLException: Failed to validate a newly established connection.
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:802)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:617)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:186)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:204)
        ... 21 more

2015-03-25 21:46:09,774 1.1.0.RELEASE  INFO task-scheduler-1 sink.gpt - {=697330}

**Comment by trisberg** [comment]
Good to know it is working. I've seen that error from the connection pool as well occasinally. I usually specify --testOnBorrow=false to avoid the problem. See if that fixes it.

**Comment by thesynapses** [comment]
Thanks everyone !!! Looks like that fixed it and ready to roll this out in a distributed cluster now.

**Comment by thomasdarimont** [comment]
Small addition:

I gave this a spin as well and can confirm, that I see an exception logged after 6 successful queries.
It seems that you need to configure the validation query appropriately: 
With:
```--validationQuery='select 1' ```
I don't see any exceptions anymore.

Cheers,
Thomas

**Comment by thesynapses** [comment]
Thanks !! I will get it a try as well.
OnTestBorrow=false seems to work fine too.


On Mar 26, 2015, at 4:08 AM, Thomas Darimont <notifications@github.com<mailto:notifications@github.com>> wrote:


Small addition:

I gave this a spin as well and can confirm, that I see an exception logged after 6 successful queries.
It seems that you need to configure the validation query appropriately:
With:
--validationQuery='select 1'
I don't see any exceptions anymore.

Cheers,
Thomas
