### ISSUE TITLE
JDBC sink cannot insert into postgres timestamp columns

### ISSUE THREAD

**Issue by akhtet** [spring-projects/spring-xd#1608]
I am streaming JSON payloads into a JDBC sink when then insert records into a Postgresql table.  While this works correctly for most postgres column types, this gives exceptions when I insert data into columns having the type "timestamp without time zone" .

The JSON string contains ISO 8601 format datetime strings.  An example of the payload string looks like this. 

    {"ts":"2015-04-16T10:45:47.000","customer_id":"12345678"}

Directly using these values in a SQL terminal works correctly.

    insert into events (customer_id, ts ) values ('12345678', '2015-04-16T10:45:47.000');
    INSERT 0 1

However, when I used the JDBC sink to process this payload, I get the following error.

    Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [insert into events (customer_id, ts) values(?, ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: column "ts" is of type timestamp without time zone but expression is of type character varying
      Hint: You will need to rewrite or cast the expression.
      Position: 104
    	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660)
    	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)
    	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:933)
    	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:313)
    	at org.springframework.integration.jdbc.JdbcMessageHandler.executeUpdateQuery(JdbcMessageHandler.java:130)
    	at org.springframework.integration.jdbc.JdbcMessageHandler.handleMessageInternal(JdbcMessageHandler.java:112)
    	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
    	... 318 more
    Caused by: org.postgresql.util.PSQLException: ERROR: column "ts" is of type timestamp without time zone but expression is of type character varying
      Hint: You will need to rewrite or cast the expression.
      Position: 104
    	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
    	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
    	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
    	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
    	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
    	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:916)
    	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:909)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
    	... 324 more
    
    2015-05-12 14:44:58,702 1.1.1.RELEASE ERROR task-scheduler-2 handler.LoggingHandler - org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.jdbc.JdbcMessageHandler#0]; nested exception is org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [insert into events (customer_id, ts) values(?, ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: column "ts" is of type timestamp without time zone but expression is of type character varying
      Hint: You will need to rewrite or cast the expression.
      Position: 105

**Comment by artembilan** [comment]
Hi @akhtet !

I'm afraid that we can't do automatic `string -> timestamp` conversion from Java.
I guess the sample above is from Postgre directly.

One solution is like this:
````sql
insert into events (customer_id, ts ) values (:payload[customer_id], to_timestamp(:payload[ts], ' yyyy-mm-dd hh24:mi:ss'));
````
Where we use a built-in Postgre function to convert string to timestamp.

Another better solution must be based on the `PreparedStatement.setTimestamp()`, which (I guess) is used by `JdbcTemplate` when it  meets Java `Date` or `Calendar` object for value to INSERT.

The `JDBC Sink` doesn't support now time objects from values, only `String` and `Number`.
However it may look like this:
````java
ObjectMapper objectMapper = new ObjectMapper();
final DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
objectMapper.setDateFormat(df);
````
That's becuase `JdbcMessagePayloadTransformer` is based on `Jackson2JsonObjectMapper` and the `--dateFormat=` can be a good option for `JDBC Sink` to deserialize time-based JSON to the Java Date and let `JdbcTemplate` to do `setTimestamp()` magic on the background.
@akhtet, you can do that with your custom `JdbcMessagePayloadTransformer`.

@trisberg, WDYT ?
