### ISSUE TITLE
error when registering custom module

### ISSUE THREAD

**Issue by constantlearner** [spring-projects/spring-xd#1773]
I have created my custom module to read a stream file format it and write to rabbit mq

I run below command to register module

module upload --type job --name messageca2 --file /Users/xyz/Downloads/spring-xd-1.2.1.RELEASE/xd/custom-modules/batch.jar
Successfully uploaded module 'job:messageca2'

then i am trying to create a job

job create --name messagerabbit2  --definition "messageca2 --makeUnique=false" --deploy 
It says Successfully created and deployed job 'messagerabbit2'

But in log console i see below errors Please let me know if i miss something

group = 'messagerabbit2', sourceChannelName = [null], sinkChannelName = [null], index = 0, type = job, parameters = map['makeUnique' -> 'false'], children = list[[empty]]]
2015-09-22T12:48:15-0500 1.2.1.RELEASE ERROR DeploymentsPathChildrenCache-0 container.DeploymentListener - Exception deploying module
java.lang.IllegalArgumentException: Required module artifacts are either missing or invalid. Unable to determine module type for module definition: 'job:messageca2'.
    at org.springframework.util.Assert.notNull(Assert.java:112) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    at org.springframework.xd.module.core.ModuleFactory.createSimpleModule(ModuleFactory.java:122) ~[spring-xd-module-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.springframework.xd.module.core.ModuleFactory.createAndConfigureModuleInstance(ModuleFactory.java:98) ~[spring-xd-module-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.springframework.xd.module.core.ModuleFactory.createModule(ModuleFactory.java:81) ~[spring-xd-module-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.springframework.xd.dirt.module.ModuleDeployer.createModule(ModuleDeployer.java:181) ~[spring-xd-dirt-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.springframework.xd.dirt.server.container.DeploymentListener.deployModule(DeploymentListener.java:363) [spring-xd-dirt-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.springframework.xd.dirt.server.container.DeploymentListener.deployJobModule(DeploymentListener.java:291) [spring-xd-dirt-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.springframework.xd.dirt.server.container.DeploymentListener.onChildAdded(DeploymentListener.java:181) [spring-xd-dirt-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.springframework.xd.dirt.server.container.DeploymentListener.childEvent(DeploymentListener.java:149) [spring-xd-dirt-1.2.1.RELEASE.jar:1.2.1.RELEASE]
    at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:509) [curator-recipes-2.6.0.jar:na]
    at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:503) [curator-recipes-2.6.0.jar:na]
    at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:92) [curator-framework-2.6.0.jar:na]
    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.1.jar:na]
    at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:83) [curator-framework-2.6.0.jar:na]
    at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:500) [curator-recipes-2.6.0.jar:na]
    at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [curator-recipes-2.6.0.jar:na]
    at org.apache.curator.framework.recipes.cache.PathChildrenCache$10.run(PathChildrenCache.java:762) [curator-recipes-2.6.0.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
2015-09-22T12:48:15-0500 1.2.1.RELEASE INFO DeploymentsPathChildrenCache-0 container.DeploymentListener - Path cache event: path=/deployments/modules/allocated/9ceb7180-59b5-417b-a5fb-3dc546056bd3/messagerabbit2.job.messageca2.1, type=CHILD_REMOVED
2015-09-22T12:48:15-0500 1.2.1.RELEASE INFO DeploymentSupervisor-0 zk.ZKJobDeploymentHandler - Deployment status for job 'messagerabbit2': DeploymentStatus{state=failed,error(s)=java.lang.IllegalArgumentException: Required module artifacts are either missing or invalid. Unable to determine module type for module definition: 'job:messageca2'.
    at org.springframework.util.Assert.notNull(Assert.java:112)
    at org.springframework.xd.module.core.ModuleFactory.createSimpleModule(ModuleFactory.java:122)
    at org.springframework.xd.module.core.ModuleFactory.createAndConfigureModuleInstance(ModuleFactory.java:98)
    at org.springframework.xd.module.core.ModuleFactory.createModule(ModuleFactory.java:81)

**Comment by wxlund** [comment]
what does your module info job:messageca2 output look like?

**Comment by trisberg** [comment]
Yes, also what is the content of /Users/xyz/Downloads/spring-xd-1.2.1.RELEASE/xd/custom-modules/batch.jar and why is it already located inside the XD custom-modules directory?

**Comment by constantlearner** [comment]
It was issue behind the proxy I was trying to build sample app within proxy and  with custom settings.xml and failed .If i use normal settings.xml it works.
