### ISSUE TITLE
kafka source module (used in composed module?) does not always shutdown promptly

### ISSUE THREAD

**Issue by clemper** [spring-projects/spring-xd#1839]
We have a number of streams that use the kafka source module within a composed module.  We have noticed an issue with our deployments where the stream reports as undeployed but the admin UI shows the module as still resident in memory in the Spring XD container.  The module eventually "times out" and goes away on its own, but this often takes up to 10 minutes or more.  

I was able to capture the following thread stack traces in the Spring XD container:

Thead waiting to put next kafka message on the queue:
```
"pool-24-thread-1" - Thread t@1449
   java.lang.Thread.State: TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at reactor.jarjar.com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:136)
	at reactor.jarjar.com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:105)
	at reactor.jarjar.com.lmax.disruptor.RingBuffer.next(RingBuffer.java:246)
	at reactor.core.processor.util.RingBufferSubscriberUtils.onNext(RingBufferSubscriberUtils.java:25)
	at reactor.core.processor.RingBufferProcessor.onNext(RingBufferProcessor.java:574)
	at org.springframework.integration.kafka.listener.QueueingMessageListenerInvoker.enqueue(QueueingMessageListenerInvoker.java:94)
	at org.springframework.integration.kafka.listener.ConcurrentMessageListenerDispatcher.dispatch(ConcurrentMessageListenerDispatcher.java:115)
	at org.springframework.integration.kafka.listener.KafkaMessageListenerContainer$FetchTask.run(KafkaMessageListenerContainer.java:397)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- locked <113e61c> (a java.util.concurrent.ThreadPoolExecutor$Worker
```

Thread waiting for an acknowledgement when processing kafka messages downstream from the kafka source in the composed module:
```
"pool-23-thread-1" - Thread t@1448
   java.lang.Thread.State: TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <4a910f7> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel.receive(GenericMessagingTemplate.java:203)
	at org.springframework.messaging.core.GenericMessagingTemplate.doReceive(GenericMessagingTemplate.java:130)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:157)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessagingTemplate.sendAndReceive(AbstractMessagingTemplate.java:42)
	at org.springframework.integration.gateway.MessagingGatewaySupport.doSendAndReceive(MessagingGatewaySupport.java:331)
	at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceiveMessage(MessagingGatewaySupport.java:302)
	at org.springframework.integration.transformer.ContentEnricher$Gateway.sendAndReceiveMessage(ContentEnricher.java:465)
	at org.springframework.integration.transformer.ContentEnricher.handleRequestMessage(ContentEnricher.java:367)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.handler.MessageHandlerChain$1.send(MessageHandlerChain.java:123)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.handler.MessageHandlerChain.handleMessageInternal(MessageHandlerChain.java:104)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:287)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:245)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:287)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:245)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:287)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:245)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:287)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:245)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:287)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:245)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:287)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:245)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:101)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:43)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$AutoAcknowledgingChannelForwardingMessageListener.doOnMessage(KafkaMessageDrivenChannelAdapter.java:171)
	at org.springframework.integration.kafka.listener.AbstractDecodingMessageListener.onMessage(AbstractDecodingMessageListener.java:50)
	at org.springframework.integration.kafka.listener.QueueingMessageListenerInvoker$KafkaMessageDispatchingSubscriber.onNext(QueueingMessageListenerInvoker.java:138)
	at org.springframework.integration.kafka.listener.QueueingMessageListenerInvoker$KafkaMessageDispatchingSubscriber.onNext(QueueingMessageListenerInvoker.java:127)
	at reactor.core.processor.util.RingBufferSubscriberUtils.route(RingBufferSubscriberUtils.java:62)
	at reactor.core.processor.RingBufferProcessor$BatchSignalProcessor.run(RingBufferProcessor.java:786)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- locked <16e3a2df> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

Thread waiting to enqueue the "stop" command on the ring buffer:

```
"main-EventThread" - Thread t@35
   java.lang.Thread.State: TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at reactor.jarjar.com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:136)
	at reactor.jarjar.com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:105)
	at reactor.jarjar.com.lmax.disruptor.RingBuffer.next(RingBuffer.java:246)
	at reactor.core.processor.util.RingBufferSubscriberUtils.onComplete(RingBufferSubscriberUtils.java:49)
	at reactor.core.processor.RingBufferProcessor.onComplete(RingBufferProcessor.java:584)
	at org.springframework.integration.kafka.listener.QueueingMessageListenerInvoker.stop(QueueingMessageListenerInvoker.java:112)
	- locked <7c9c6876> (a org.springframework.integration.kafka.listener.QueueingMessageListenerInvoker)
	at org.springframework.integration.kafka.listener.ConcurrentMessageListenerDispatcher$StopDelegateProcedure.value(ConcurrentMessageListenerDispatcher.java:145)
	at org.springframework.integration.kafka.listener.ConcurrentMessageListenerDispatcher$StopDelegateProcedure.value(ConcurrentMessageListenerDispatcher.java:139)
	at com.gs.collections.impl.set.mutable.UnifiedSet.forEachWith(UnifiedSet.java:626)
	at org.springframework.integration.kafka.listener.ConcurrentMessageListenerDispatcher.stop(ConcurrentMessageListenerDispatcher.java:107)
	- locked <41bb3e69> (a java.lang.Object)
	at org.springframework.integration.kafka.listener.KafkaMessageListenerContainer.stop(KafkaMessageListenerContainer.java:281)
	- locked <b07f51c> (a java.lang.Object)
	at org.springframework.integration.kafka.listener.KafkaMessageListenerContainer.stop(KafkaMessageListenerContainer.java:318)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.doStop(KafkaMessageDrivenChannelAdapter.java:142)
	at org.springframework.integration.endpoint.AbstractEndpoint.doStop(AbstractEndpoint.java:145)
	at org.springframework.integration.endpoint.AbstractEndpoint.stop(AbstractEndpoint.java:128)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:229)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:51)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:363)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:202)
	at org.springframework.context.support.DefaultLifecycleProcessor.stop(DefaultLifecycleProcessor.java:106)
	at org.springframework.context.support.AbstractApplicationContext.stop(AbstractApplicationContext.java:1175)
	at org.springframework.xd.module.core.SimpleModule.stop(SimpleModule.java:244)
	at org.springframework.xd.module.core.CompositeModule.stop(CompositeModule.java:280)
	at org.springframework.xd.module.core.CompositeModule.stop(CompositeModule.java:280)
	at org.springframework.xd.dirt.module.ModuleDeployer.destroyModule(ModuleDeployer.java:279)
	at org.springframework.xd.dirt.module.ModuleDeployer.undeploy(ModuleDeployer.java:260)
	- locked <79c5712b> (a org.springframework.xd.dirt.module.ModuleDeployer)
	at org.springframework.xd.dirt.server.container.DeploymentListener.undeployModule(DeploymentListener.java:390)
	at org.springframework.xd.dirt.server.container.DeploymentListener$StreamModuleWatcher.process(DeploymentListener.java:567)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:67)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)

   Locked ownable synchronizers:
	- locked <6a03ff5> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

Based on these thread stack traces, I suspect what is happening is that the some Spring integration component downstream from the kafka source gets shutdown immediately, and so the messages just timeout rather than causing an immediate error.  This causes the "working through the queue" to take longer, so it also takes longer for the ring buffer to accept and process the "stop" command. 

Thanks,
@clemper

**Comment by mbogoevici** [comment]
Hi @clemper,

Thanks for reporting this. I suspect that this is an issue with the `KafkaMessageListenerContainer` shutdown. Will try to include in the fixes for 1.3.

Cheers,
Marius

**Comment by artembilan** [comment]
Hi @clemper !

Would you mind to share your experience how does it work if you configure `KafkaMessageListenerContainer` with the injected `dispatcherTaskExecutor`?
Because I'm afraid we have a problem with non-stopped Thread from the default internal:
```
ExecutorService service = executorService != null ? executorService : Executors.newSingleThreadExecutor();
```

Thank you for reporting this!

**Comment by mbogoevici** [comment]
Since this is coming from Spring XD, there probably is no custom task executor ...

**Comment by artembilan** [comment]
Sorry, it won't help. Just because `Executors.newSingleThreadExecutor()` is like:
```
static class FinalizableDelegatedExecutorService
        extends DelegatedExecutorService {
        FinalizableDelegatedExecutorService(ExecutorService executor) {
            super(executor);
        }
        protected void finalize() {
            super.shutdown();
        }
    }
```
So, it will be `shutdown()` on the next GC when we do:
```
ringBufferProcessor.onComplete();
ringBufferProcessor = null;
```
I can reproduce it, BTW:
````xml
<int-kafka:message-driven-channel-adapter
			id="adapter"
			channel="output"
			connection-factory="connectionFactory"
			key-decoder="decoder"
			payload-decoder="decoder"
			max-fetch="100"
			stop-timeout="10000"
			topics="${kafka.test.topic}"/>

	<int:enricher input-channel="output" reply-timeout="-1"
				  request-channel="process"/>

	<int:channel id="process">
		<int:queue/>
	</int:channel>
````
Pay attention to the `stop-timeout="10000"` and ` reply-timeout="-1"`.
The last one said that we will wait for the reply forever. And it is a fact with our hacky `process` doewnstream.
But anyway the container waits for the stop exactly those 10 secs on the : 
```
ringBufferProcessor.onComplete();
ringBufferProcessor = null;
try {
	shutdownLatch.await(stopTimeout, TimeUnit.MILLISECONDS);
}
```
And than application stop() correctly with the logs:
```
19:26:46.710 DEBUG [pool-5-thread-1][org.springframework.integration.channel.QueueChannel] postSend (sent=true) on channel 'process', message: GenericMessage [payload=Message 0, headers={replyChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@541da6cd, kafka_offset=0, errorChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@541da6cd, kafka_messageKey=Key 0, kafka_topic=test-topic, kafka_partitionId=0, kafka_nextOffset=1, id=a9a74217-244e-e75c-f4ed-eaf522086685, timestamp=1446510406710}]
19:26:58.669 INFO  [main][org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter] stopped adapter
19:26:58.669 INFO  [main][org.springframework.integration.endpoint.EventDrivenConsumer] Removing {enricher} as a subscriber to the 'output' channel
```

**Comment by artembilan** [comment]
For my test-case I modified config for `ChannelAdapterWithXmlConfigurationTests` that way. And the code like:
```
ClassPathXmlApplicationContext context =
				new ClassPathXmlApplicationContext("ChannelAdapterWithXmlConfigurationTests-context.xml",
				ChannelAdapterWithXmlConfigurationTests.class);

		Thread.sleep(2000);

		context.stop();

/*		QueueChannel output = context.getBean("output", QueueChannel.class);

		for (int i = 0; i < 100; i++) {
			Message<?> received = output.receive(1000);
			Assert.assertThat(received, notNullValue());
		}*/
```
