### ISSUE TITLE
Embedded message headers does not support multibyte header values

### ISSUE THREAD

**Issue by clemper** [spring-projects/spring-xd#1871]
It looks like the Kafka message bus (and probably the Redis bus) throws a java.nio.BufferOverflowException if any header values contain a multibyte character. 

```Java
	@Test
	public void testMultibyteHeaderValues() throws Exception {
		EmbeddedHeadersMessageConverter converter = new EmbeddedHeadersMessageConverter();
		String payload = "Hello";
		String multibyteHeaderName = "multibyteHeader";
		String multibyteHeaderValue = "ØØØØØØØØ";
		Message<byte[]> message = MessageBuilder.withPayload(payload.getBytes()).setHeader(multibyteHeaderName,
				multibyteHeaderValue).build();
		byte[] embedded = converter.embedHeaders(new MessageValues(message), multibyteHeaderName);
		Message<byte[]> kafkaMessage = MessageBuilder.withPayload(embedded).build();
		MessageValues extracted = converter.extractHeaders(kafkaMessage, true);
		assertEquals(payload, new String((byte[]) extracted.getPayload()));
		assertEquals(multibyteHeaderValue, extracted.get(multibyteHeaderName));
	}
```

```
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at org.springframework.xd.dirt.integration.bus.EmbeddedHeadersMessageConverter.embedHeaders(EmbeddedHeadersMessageConverter.java:87)
	at org.springframework.xd.dirt.integration.bus.MessageConverterTests.testMultibyteHeaderValues(MessageConverterTests.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

The root issue is that the length of a String containing a multibyte character is not equal to the number of bytes in UTF-8 character encoding.

https://github.com/spring-projects/spring-xd/blob/master/spring-xd-messagebus-spi/src/main/java/org/springframework/xd/dirt/integration/bus/EmbeddedHeadersMessageConverter.java#L71

Thanks,
Chris

**Comment by garyrussell** [comment]
Thanks; I've opened [this JIRA](https://jira.spring.io/browse/XD-3725) to track this.

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-xd/pull/1872

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-projects/spring-xd/commit/e5334d7934b8a6886fe1ad42515011ffd27cca61
