### ISSUE TITLE
New install of Hue 3.8 not working for PHD 3.0

### ISSUE THREAD

**Issue by yaducool** [spring-projects/spring-xd#1890]
Hi,

I have installed Hue 3.8 on PHD 3.0 cluster and the installation was successful. But the HUE web page is stuck on 'check configuration page'. I see the below error in the log

[16/Feb/2016 03:06:33 -0800] connectionpool INFO     Starting new HTTP connection (1): hdp-prd-mst1.abc.com
[16/Feb/2016 03:06:33 -0800] access       INFO     10.107.64.122 admin - "GET /desktop/debug/check_config HTTP/1.1"
[16/Feb/2016 03:06:33 -0800] connectionpool INFO     Starting new HTTP connection (1): phdprod.abc.com
[16/Feb/2016 03:06:33 -0800] webhdfs      ERROR    Failed to determine superuser of WebHdfs at http://phdprod.abc.com:8082/webhdfs/v1: SecurityException: Failed to get token for `3: hue': No such file or directory (error 401)
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 142, in superuser
    sb = self.stats('/')
  File "/usr/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 229, in stats
    res = self._stats(path)
  File "/usr/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 223, in _stats
    raise ex
WebHdfsException: SecurityException: Failed to get token for `3: hue': No such file or directory (error 401)
[16/Feb/2016 03:06:33 -0800] connectionpool INFO     Starting new HTTP connection (1): localhost
[16/Feb/2016 03:06:33 -0800] connectionpool INFO     Starting new HTTP connection (1): phdprod.abc.com
[16/Feb/2016 03:06:33 -0800] hive_server2_lib INFO     use_sasl=True, mechanism=PLAIN, kerberos_principal_short_name=None, impersonation_enabled=True
[16/Feb/2016 03:

Please help!

Thanks,
Yadu

**Comment by sabbyanandan** [comment]
Hi @yaducool: This error is not related to Spring XD. You'd have to reach out to PHD support instead. Closing this issue.
