### ISSUE TITLE
Stream failover doesn't work

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-xd#1924]
XD installed via ambari plugin. 

Having two containers, ambari-4, ambari-5

```
xd:>stream create --name ticktock --definition "time|log" --deploy 
Created and deployed new stream 'ticktock'

xd:>stream list
  Stream Name  Stream Definition  Status
  -----------  -----------------  --------
  ticktock     time|log           deployed

xd:>runtime modules 
  Module Id               Container Id                          Options                                                                                      Deployment Properties                                         Unit status
  ----------------------  ------------------------------------  -------------------------------------------------------------------------------------------  ------------------------------------------------------------  -----------
  ticktock.sink.log.1     09ec4357-e4cb-409c-923e-b41415489798  {name=ticktock, expression=payload, level=INFO}                                              {consumer.sequence=1, count=1, consumer.count=1, sequence=1}  deployed
  ticktock.source.time.1  fc6d2d4a-cc22-44a2-8136-e75f5aa24deb  {maxMessages=1, initialDelay=0, fixedDelay=1, format=yyyy-MM-dd HH:mm:ss, timeUnit=SECONDS}  {producer.next.module.count=1, count=1, sequence=1}           deployed

xd:>runtime containers
  Container Id                          Host                  IP Address      PID    Groups  Custom Attributes
  ------------------------------------  --------------------  --------------  -----  ------  -----------------
  b7a4ccb5-3b8d-470f-81c1-05067ee9105a  ambari-5.localdomain  172.16.101.145  11181
  fc6d2d4a-cc22-44a2-8136-e75f5aa24deb  ambari-4.localdomain  172.16.101.144  4390
```

shutdown ambari-5, log sink is started on ambari-4

ambari-5 container log:
```
2017-01-31T05:19:42-0800 1.3.1.RELEASE INFO main-EventThread container.DeploymentListener - Undeploying module [ModuleDescriptor@10f823d2 moduleName = 'log', moduleLabel = 'log', group = 'ticktock', sourceChannelName = [null], sinkChannelName = [null], index = 1, type = sink, parameters = map[[empty]], children = list[[empty]]]
```

```
xd:>runtime modules 
  Module Id               Container Id                          Options                                                                                      Deployment Properties                                         Unit status
  ----------------------  ------------------------------------  -------------------------------------------------------------------------------------------  ------------------------------------------------------------  -----------
  ticktock.sink.log.1     fc6d2d4a-cc22-44a2-8136-e75f5aa24deb  {name=ticktock, expression=payload, level=INFO}                                              {consumer.sequence=1, count=1, consumer.count=1, sequence=1}  deployed
  ticktock.source.time.1  fc6d2d4a-cc22-44a2-8136-e75f5aa24deb  {maxMessages=1, initialDelay=0, fixedDelay=1, format=yyyy-MM-dd HH:mm:ss, timeUnit=SECONDS}  {producer.next.module.count=1, count=1, sequence=1}           deployed
```

bring ambari-5 up, then shutdown(graceful shutdown, not kill) ambari-4

ambari-4 container log:
```
2017-01-31T05:23:31-0800 1.3.1.RELEASE INFO main-EventThread container.DeploymentListener - Undeploying module [ModuleDescriptor@60579fc6 moduleName = 'log', moduleLabel = 'log', group = 'ticktock', sourceChannelName = [null], sinkChannelName = [null], index = 1, type = sink, parameters = map[[empty]], children = list[[empty]]]
2017-01-31T05:23:31-0800 1.3.1.RELEASE INFO main-EventThread container.DeploymentListener - Undeploying module [ModuleDescriptor@22d6cc11 moduleName = 'time', moduleLabel = 'time', group = 'ticktock', sourceChannelName = [null], sinkChannelName = [null], index = 0, type = source, parameters = map[[empty]], children = list[[empty]]]
```

admin server log:
```
2017-01-31T05:23:31-0800 1.3.1.RELEASE INFO DeploymentSupervisor-0 zk.ContainerListener - Container departed: Container{name='fc6d2d4a-cc22-44a2-8136-e75f5aa24deb', attributes={ip=172.16.101.144, host=ambari-4.localdomain, groups=, pid=4390, id=fc6d2d4a-cc22-44a2-8136-e75f5aa24deb}}
2017-01-31T05:23:33-0800 1.3.1.RELEASE INFO DeploymentSupervisor-0 zk.ModuleRedeployer - Deployment state for stream 'ticktock': DeploymentStatus{state=failed}
```

ambari-5 container log then shows:
```
2017-01-31T05:23:31-0800 1.3.1.RELEASE INFO DeploymentsPathChildrenCache-0 container.DeploymentListener - Path cache event: path=/deployments/modules/allocated/b7a4ccb5-3b8d-470f-81c1-05067ee9105a/ticktock.source.time.1, type=CHILD_ADDED
2017-01-31T05:23:31-0800 1.3.1.RELEASE INFO DeploymentsPathChildrenCache-0 container.DeploymentListener - Deploying module 'time' for stream 'ticktock'
2017-01-31T05:23:31-0800 1.3.1.RELEASE INFO DeploymentsPathChildrenCache-0 container.DeploymentListener - Deploying module [ModuleDescriptor@336353cd moduleName = 'time', moduleLabel = 'time', group = 'ticktock', sourceChannelName = [null], sinkChannelName = [null], index = 0, type = source, parameters = map[[empty]], children = list[[empty]]]
2017-01-31T05:23:33-0800 1.3.1.RELEASE WARN DeploymentsPathChildrenCache-0 producer.ProducerConfig - The configuration value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer was supplied but isn't a known config.
2017-01-31T05:23:33-0800 1.3.1.RELEASE WARN DeploymentsPathChildrenCache-0 producer.ProducerConfig - The configuration key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer was supplied but isn't a known config.

2017-01-31T05:33:33-0800 1.3.1.RELEASE WARN kafka-producer-network-thread | producer-1 network.Selector - Error in I/O with ambari-2.localdomain/172.16.101.142
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62) ~[kafka-clients-0.8.2.2.jar:na]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:248) ~[kafka-clients-0.8.2.2.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [kafka-clients-0.8.2.2.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [kafka-clients-0.8.2.2.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [kafka-clients-0.8.2.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

```

and runtime shows failure
```
xd:>runtime modules 
  Module Id               Container Id                          Options                                                                                      Deployment Properties                                Unit status
  ----------------------  ------------------------------------  -------------------------------------------------------------------------------------------  ---------------------------------------------------  -----------
  ticktock.source.time.1  b7a4ccb5-3b8d-470f-81c1-05067ee9105a  {maxMessages=1, initialDelay=0, fixedDelay=1, format=yyyy-MM-dd HH:mm:ss, timeUnit=SECONDS}  {producer.next.module.count=1, count=1, sequence=1}  failed
```

**Comment by jvalkeal** [comment]
Enabled more logging and this is what happens in admin server when I kill node having both modules for ticktock stream:
```
2017-02-01T02:03:38-0800 1.3.1.RELEASE INFO DeploymentSupervisor-0 zk.ContainerListener - Container departed: Container{name='76cca555-5379-4b0a-81b9-66e701ab9b3a', attributes={ip=172.16.101.145, host=ambari-5.localdomain, groups=, pid=8441, id=76cca555-5379-4b0a-81b9-66e701ab9b3a}}
2017-02-01T02:03:38-0800 1.3.1.RELEASE DEBUG DeploymentSupervisor-0 options.FlattenedCompositeModuleOptionsMetadata - returning propertyNames: fixedDelay,maxMessages,format,initialDelay,timeUnit
2017-02-01T02:03:38-0800 1.3.1.RELEASE DEBUG DeploymentSupervisor-0 deployment.ContainerMatcher - Matching containers for module [ModuleDescriptor@f2a7686 moduleName = 'time', moduleLabel = 'time', group = 'foostream', sourceChannelName = [null], sinkChannelName = [null], index = 0, type = source, parameters = map[[empty]], children = list[[empty]]]
2017-02-01T02:03:38-0800 1.3.1.RELEASE TRACE DeploymentSupervisor-0 deployment.ContainerMatcher - Evaluating container Container{name='caecfd26-89bd-4843-a86f-102dd7e5a936', attributes={ip=172.16.101.144, host=ambari-4.localdomain, groups=, pid=8575, id=caecfd26-89bd-4843-a86f-102dd7e5a936}}
2017-02-01T02:03:38-0800 1.3.1.RELEASE TRACE DeploymentSupervisor-0 deployment.ContainerMatcher - 	Added container Container{name='caecfd26-89bd-4843-a86f-102dd7e5a936', attributes={ip=172.16.101.144, host=ambari-4.localdomain, groups=, pid=8575, id=caecfd26-89bd-4843-a86f-102dd7e5a936}}
2017-02-01T02:03:38-0800 1.3.1.RELEASE DEBUG DeploymentSupervisor-0 options.FlattenedCompositeModuleOptionsMetadata - returning propertyNames: fixedDelay,maxMessages,format,initialDelay,timeUnit

2017-02-01T02:03:40-0800 1.3.1.RELEASE TRACE main-EventThread zk.ModuleDeploymentWriter - EventCollector received event: WatchedEvent state:SyncConnected type:NodeDataChanged path:/deployments/modules/allocated/caecfd26-89bd-4843-a86f-102dd7e5a936/foostream.source.time.1/status
2017-02-01T02:03:40-0800 1.3.1.RELEASE TRACE DeploymentSupervisor-0 zk.ModuleRedeployer - module deployment status: ModuleDeploymentStatus{container='caecfd26-89bd-4843-a86f-102dd7e5a936', moduleSequence=1, key=ModuleDeploymentKey{stream='foostream', type=source, label='time'}, state=deployed, errorDescription='null'}
2017-02-01T02:03:40-0800 1.3.1.RELEASE TRACE DeploymentSupervisor-0 zk.ModuleRedeployer - deploymentStatus: ModuleDeploymentStatus{container='caecfd26-89bd-4843-a86f-102dd7e5a936', moduleSequence=1, key=ModuleDeploymentKey{stream='foostream', type=source, label='time'}, state=deployed, errorDescription='null'}
2017-02-01T02:03:40-0800 1.3.1.RELEASE DEBUG DeploymentSupervisor-0 deployment.DefaultDeploymentUnitStateCalculator - Evaluating state for foostream
2017-02-01T02:03:40-0800 1.3.1.RELEASE TRACE DeploymentSupervisor-0 deployment.DefaultDeploymentUnitStateCalculator - moduleCountMap: {ModuleDeploymentKey{stream='foostream', type=sink, label='log'}=Count{expected=1, actual=0}, ModuleDeploymentKey{stream='foostream', type=source, label='time'}=Count{expected=1, actual=0}}
2017-02-01T02:03:40-0800 1.3.1.RELEASE TRACE DeploymentSupervisor-0 deployment.DefaultDeploymentUnitStateCalculator - 	ModuleDeploymentStatus{container='caecfd26-89bd-4843-a86f-102dd7e5a936', moduleSequence=1, key=ModuleDeploymentKey{stream='foostream', type=source, label='time'}, state=deployed, errorDescription='null'}
2017-02-01T02:03:40-0800 1.3.1.RELEASE TRACE DeploymentSupervisor-0 deployment.DefaultDeploymentUnitStateCalculator - moduleCountMap after evaluation: {ModuleDeploymentKey{stream='foostream', type=sink, label='log'}=Count{expected=1, actual=0}}
2017-02-01T02:03:40-0800 1.3.1.RELEASE INFO DeploymentSupervisor-0 zk.ModuleRedeployer - Deployment state for stream 'foostream': DeploymentStatus{state=failed}
```

- Looks like it is deploying `time` first.
- Looking container log, time module works fine as it's sending timestamps to kafka
- admin server ends with message that stream failed because `log` module is not there.

If I simply bounce containers, re-deployment happens ok but log is deployed first and then time. Maybe this is the culprit that `ModuleRedeployer` tries to deploy on wrong order?

**Comment by ilayaperumalg** [comment]
@jvalkeal One of the main goals of the ModuleRedeployer (in this case it is `DepartedContainerModuleRedeployer`) is to re-deploy the stream modules in the correct order and it is done specifically [here](https://github.com/spring-projects/spring-xd/blob/master/spring-xd-dirt/src/main/java/org/springframework/xd/dirt/server/admin/deployment/zk/DepartedContainerModuleRedeployer.java#L104). The `ModuleDeployment` holds the order of the stream modules based on the index. Wondering how the order is an issue here.

**Comment by jvalkeal** [comment]
I added some logging around [DepartedContainerModuleRedeployer.java#L153](https://github.com/spring-projects/spring-xd/blob/master/spring-xd-dirt/src/main/java/org/springframework/xd/dirt/server/admin/deployment/zk/DepartedContainerModuleRedeployer.java#L153) to see what's in `streamModuleDeployments`.

```
2017-02-01T04:14:18-0800 1.3.2.SNAP INFO DeploymentSupervisor-0 zk.DepartedContainerModuleRedeployer - XXX1 listing streamModuleDeployments
2017-02-01T04:14:18-0800 1.3.2.SNAP INFO DeploymentSupervisor-0 zk.DepartedContainerModuleRedeployer - XXX2 moduleDeployment.deploymentUnit Stream{name='foostream'}
2017-02-01T04:14:18-0800 1.3.2.SNAP INFO DeploymentSupervisor-0 zk.DepartedContainerModuleRedeployer - XXX2 moduleDeployment.moduleDescriptor [ModuleDescriptor@2df1b274 moduleName = 'time', moduleLabel = 'time', group = 'foostream', sourceChan
```

Which means that if I kill container having both ticktock modules, only `time` is redeployed. Where did `log` go is a good question.

**Comment by jvalkeal** [comment]
ok, in [DepartedContainerModuleRedeployer.java#L107](https://github.com/spring-projects/spring-xd/blob/master/spring-xd-dirt/src/main/java/org/springframework/xd/dirt/server/admin/deployment/zk/DepartedContainerModuleRedeployer.java#L107) I can see that both `time` and `log` are there.

However in [DepartedContainerModuleRedeployer.java#L136](https://github.com/spring-projects/spring-xd/blob/master/spring-xd-dirt/src/main/java/org/springframework/xd/dirt/server/admin/deployment/zk/DepartedContainerModuleRedeployer.java#L136) `stream` is null with first iteration and deployment is added. In second iteration(which is for log) `stream` is not null anymore thus we don't add anything to `streamModuleDeployments`. Thus we're just left with `time` or whatever was first in `deployments` list.

**Comment by jvalkeal** [comment]
Yeah, it's pretty clear now as how that `streamMap` is used. It never have a change to add further deployments due to way conditions are used in that if clause.
