### ISSUE TITLE
syslogtcp - payload must be string or byte[]

### ISSUE THREAD

**Issue by abennet** [spring-projects/spring-xd#598]
Same simple pipeline (syslog-tcp to log). I sometimes get the following errors:
I can't figure out what types of messages are causing this problem. I can't reproduce it with a single message, it only happens when I have a lot of incoming messages on the tcp port. 
I noticed I could trigger the error if I shut down the rsyslog transmission on the client, but there is definitely other triggers to it as well. 
````
Exception in thread "pool-6-thread-320" org.springframework.messaging.MessagingException: java.lang.IllegalArgumentException: payload must be String or byte[]
	at org.springframework.integration.syslog.inbound.SyslogReceivingChannelAdapterSupport.convertAndSend(SyslogReceivingChannelAdapterSupport.java:76)
	at org.springframework.integration.syslog.inbound.TcpSyslogReceivingChannelAdapter.onMessage(TcpSyslogReceivingChannelAdapter.java:80)
	at org.springframework.integration.ip.tcp.connection.TcpConnectionSupport.sendExceptionToListener(TcpConnectionSupport.java:346)
	at org.springframework.integration.ip.tcp.connection.AbstractConnectionFactory$1.run(AbstractConnectionFactory.java:609)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalArgumentException: payload must be String or byte[]
	at org.springframework.util.Assert.isTrue(Assert.java:65)
	at org.springframework.integration.transformer.SyslogToMapTransformer.transformPayload(SyslogToMapTransformer.java:143)
	at org.springframework.integration.transformer.SyslogToMapTransformer.transformPayload(SyslogToMapTransformer.java:39)
	at org.springframework.integration.transformer.AbstractPayloadTransformer.doTransform(AbstractPayloadTransformer.java:33)
	at org.springframework.integration.syslog.DefaultMessageConverter.fromSyslog(DefaultMessageConverter.java:47)
	at org.springframework.integration.syslog.inbound.SyslogReceivingChannelAdapterSupport.convertAndSend(SyslogReceivingChannelAdapterSupport.java:73)
````

**Comment by sabbyanandan** [comment]
Improvements to ```syslog``` SI adapter is [complete](https://github.com/spring-projects/spring-integration/pull/1061). @abennet: if you run into this issue again, or have other details to share, please let us know.
